// <auto-generated />
namespace Squirrel.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addpublishdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpublishdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201502231122158_add-publishdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
