// <auto-generated />
namespace Squirrel.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class issueIdchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(issueIdchange));
        
        string IMigrationMetadata.Id
        {
            get { return "201503161220139_issueId-change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
